name=ESPBLESDK
version=0.1.0-beta.1
author=Naseem Shawarba
maintainer=Naseem Shawarba
sentence=Typed Web Bluetooth SDK for ESP32
paragraph=Pairs with the esp-ble-sdk npm package.
category=Communication
url=https://github.com/naseem-shawarba/esp-ble-sdk
architectures=esp32
includes=ESPBLESDK.h
depends=ArduinoJson